### ISSUE TITLE
Cannot run the docker image for AnnoySearcher

### ISSUE THREAD

**Issue by numb3r3** [jina-ai/executor-indexers#32]
1. build docker image for executor in https://github.com/jina-ai/executor-indexers/tree/main/jinahub/indexers/searcher/vector/AnnoySearcher

```
$ docker build . -t annoy_searcher
```
2. run the docker image 

```
$ run -it --rm  annoy_searcher
```
The following is the error log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 81, in _load_executor
    runtime_args=vars(self.args),
  File "/usr/local/lib/python3.7/site-packages/jina/jaml/__init__.py", line 536, in load_config
    return JAML.load(tag_yml, substitute=False)
  File "/usr/local/lib/python3.7/site-packages/jina/jaml/__init__.py", line 89, in load
    r = yaml.load(stream, Loader=JinaLoader)
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 429, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!AnnoyIndexer'
  in "<unicode string>", line 1, column 1:
    !AnnoyIndexer
    ^

The above exception was the direct cause of the following exception:

```

**Comment by numb3r3** [comment]
Same errors happen for https://github.com/jina-ai/executor-indexers/tree/main/jinahub/indexers/searcher/vector/NumpySearcher
